from __future__ import annotations
from typing import Any
from soctriage.core.soc_provider import HangRule

AMD_IP_BLOCKS: list[str] = [
    "GFX", "SDMA", "GMC", "VCN", "PSP", "RLC",
    "MEC", "KFD", "IH", "DCN", "MMHUB", "GCHUB", "JPEG", "SMU",
]

# IP_PATTERNS kept for scaffold compatibility (detection keyword patterns per IP)
IP_PATTERNS: dict[str, list[tuple[str, float]]] = {}

# (token_type, raw_substring, ip, confidence, subsystem)
CLASSIFY_RULES: list[tuple[str, str, str, float, str]] = [
    ("gpu_event",       "gfx",         "GFX",   0.90, "gpu"),
    ("gpu_event",       "sdma",        "SDMA",  0.90, "gpu"),
    ("gpu_event",       "vcn",         "VCN",   0.90, "gpu"),
    ("gpu_event",       "jpeg",        "JPEG",  0.88, "gpu"),
    ("gpu_event",       "",            "GFX",   0.75, "gpu"),
    ("reset_event",     "GPU reset",   "GFX",   0.85, "gpu"),
    ("reset_event",     "amdgpu",      "GFX",   0.80, "gpu"),
    ("timeout_event",   "ring",        "GFX",   0.80, "gpu"),
    ("timeout_event",   "",            "MEC",   0.70, "gpu"),
    ("memory_event",    "VRAM",        "MMHUB", 0.90, "memory"),
    ("memory_event",    "mmhub",       "MMHUB", 0.90, "memory"),
    ("memory_event",    "GMC",         "GMC",   0.88, "memory"),
    ("memory_event",    "",            "GMC",   0.75, "memory"),
    ("memory_poison",   "HBM",         "GMC",   0.95, "memory"),
    ("memory_poison",   "ECC",         "GMC",   0.92, "memory"),
    ("ras_event",       "RAS",         "RLC",   0.95, "debug"),
    ("ras_event",       "UE",          "RLC",   0.90, "debug"),
    ("ras_event",       "CE",          "RLC",   0.88, "debug"),
    ("amd_psp_fw_fail", "",            "PSP",   0.98, "firmware"),
    ("amd_psp_event",   "PSP",         "PSP",   0.90, "firmware"),
    ("amd_psp_event",   "",            "PSP",   0.82, "firmware"),
    ("amd_sev_event",   "SEV",         "PSP",   0.95, "security"),
    ("amd_tee_event",   "TEE",         "PSP",   0.92, "security"),
    ("amd_hsmp_event",  "HSMP",        "GFX",   0.88, "soc_platform"),
    ("amd_nbio_event",  "NBIO",        "IH",    0.88, "interconnect"),
    ("smmu_fault",      "AMD IOMMU",   "IH",    0.85, "interconnect"),
    ("smmu_fault",      "amd_iommu",   "IH",    0.85, "interconnect"),
    ("pcie_error",      "NBIO",        "IH",    0.85, "interconnect"),
    ("pcie_error",      "",            "IH",    0.78, "interconnect"),
    ("power_event",     "PMFW",        "SMU",   0.88, "power"),
    ("power_event",     "voltage",     "SMU",   0.80, "power"),
    ("thermal_event",   "TJ_MAX",      "SMU",   0.90, "power"),
    ("thermal_event",   "TDP",         "SMU",   0.88, "power"),
    ("thermal_event",   "temp",        "SMU",   0.78, "power"),
    ("display_event",   "DCN",         "DCN",   0.88, "display"),
    ("display_event",   "CRTC",        "DCN",   0.85, "display"),
    ("encoder_event",   "VCN",         "VCN",   0.88, "display"),
]

CASCADE_GRAPH: dict[str, list[str]] = {
    "PSP":   ["GFX", "SDMA", "VCN"],
    "GMC":   ["GFX", "SDMA"],
    "MMHUB": ["GFX", "SDMA"],
    "IH":    ["GFX", "SDMA", "VCN"],
    "SMU":   ["GFX"],
    "GFX":   ["KFD", "MEC"],
    "RLC":   ["GFX", "SDMA"],
    "MEC":   ["GFX"],
}

PLAYBOOK: dict[str, dict[str, Any]] = {
    "PSP": {
        "steps": [
            "Verify signed firmware package is installed",
            "Check Secure Boot key enrollment for amdgpu",
            "Try: modprobe -r amdgpu && modprobe amdgpu",
            "Update to latest linux-firmware package",
        ],
        "references": [],
        "notes": "PSP firmware load failure — often caused by unsigned firmware or Secure Boot mismatch.",
    },
    "GFX": {
        "steps": [
            "Capture GPU state: cat /sys/kernel/debug/dri/0/amdgpu_gpu_recover",
            "Check GFX ring: dmesg | grep 'amdgpu.*ring'",
            "Try: echo 1 > /sys/kernel/debug/dri/0/amdgpu_gpu_recover",
            "Set scheduler: amdgpu.sched_hw_submission=32",
        ],
        "references": ["https://gitlab.freedesktop.org/drm/amd/issues/3421"],
        "notes": "GFX engine hang — check CP_STALLED status register.",
    },
    "GMC": {
        "steps": [
            "Check ECC errors: dmesg | grep -i ecc",
            "Enable ECC: amdgpu.ras_enable=1",
            "Test VRAM: run memtest with GPU memory test",
            "For HBM: check thermal conditions",
        ],
        "references": [],
        "notes": "Memory/GMC fault — ECC errors or VRAM corruption.",
    },
    "SMU": {
        "steps": [
            "Check power limits: cat /sys/class/drm/card0/device/hwmon/hwmon*/power1_cap",
            "Reduce TDP: echo 150000000 > /sys/class/drm/card0/device/hwmon/hwmon*/power1_cap",
            "Verify cooling: check thermal paste and fan RPM",
            "Update PMFW via linux-firmware",
        ],
        "references": [],
        "notes": "SMU power management fault — thermal or voltage issue.",
    },
    "IH": {
        "steps": [
            "Check NBIO errors: dmesg | grep -i nbio",
            "Try PCIe reset: echo 1 > /sys/bus/pci/devices/.../reset",
            "Verify PCIe slot power delivery",
        ],
        "references": [],
        "notes": "Interrupt Handler / NBIO fault — often PCIe or IOMMU related.",
    },
}

REGISTER_MAPS: dict[str, dict[int, str]] = {
    "GRBM_STATUS": {
        0x80000000: "GUI_ACTIVE",
        0x40000000: "CP_RQ_PENDING",
        0x20000000: "CP_ME_BUSY",
        0x10000000: "CP_PFP_BUSY",
        0x00000400: "SPI_BUSY",
        0x00000080: "TA_BUSY",
    },
    "CP_STALLED_STAT1": {
        0x80000000: "RBIU_TO_DMA_NOT_RDY_TO_RCV",
        0x40000000: "RBIU_TO_SEM_NOT_RDY_TO_RCV",
        0x00000001: "CP_STALLED_STAT1_BIT0",
    },
    "SDMA0_STATUS_REG": {
        0x00000001: "SDMA_IDLE",
        0x00000002: "SDMA_BUSY",
        0x80000000: "SDMA_HANG",
    },
    "PSP_BOOTLOADER_STATUS": {
        0x00000001: "PSP_BL_LOADED",
        0x00000002: "PSP_SOS_LOADED",
        0x80000000: "PSP_FAULT",
    },
}

HANG_RULES: list[HangRule] = [
    HangRule(mode="HANG",      signals=[r"amdgpu.*hang", r"GPU HANG"],           confidence=0.90),
    HangRule(mode="ERROR",     signals=[r"RAS.*UE", r"uncorrectable.*ECC"],       confidence=0.95),
    HangRule(mode="ERROR",     signals=[r"PSP.*fail", r"amdgpu_psp.*error"],      confidence=0.92),
    HangRule(mode="STALL",     signals=[r"CP_STALLED", r"GFX.*stall"],           confidence=0.80),
    HangRule(mode="HARD-HANG", signals=[r"amdgpu.*reset failed"],                confidence=0.95),
]

KNOWN_ISSUES: list[dict[str, Any]] = [
    {
        "issue_id": "AMD-MI300-001",
        "title": "MMHUB stall during multi-tenant xGMI peer mapping on MI300X",
        "chip_gens": ["amd_cdna3"],
        "symptoms": ["gpu_hang", "memory_event", "reset_event"],
        "workaround": "Disable xGMI peer mapping: amdgpu.xgmi_pstate=0",
        "fixed_in": "6.8.0",
        "severity": "critical",
        "url": "https://gitlab.freedesktop.org/drm/amd/issues/3421",
    },
    {
        "issue_id": "AMD-MI200-001",
        "title": "Aldebaran RAS UE storm causing host kernel panic",
        "chip_gens": ["amd_cdna2"],
        "symptoms": ["ras_event", "memory_poison", "kernel_panic"],
        "workaround": "Enable RAS CE storm suppression: amdgpu.ras_mask=0x1",
        "fixed_in": "6.5.0",
        "severity": "critical",
        "url": "",
    },
    {
        "issue_id": "AMD-PSP-001",
        "title": "PSP firmware load failure on Navi31 with unsigned firmware",
        "chip_gens": ["amd_rdna3"],
        "symptoms": ["amd_psp_fw_fail", "firmware_event"],
        "workaround": "Enable Secure Boot or use signed firmware package",
        "fixed_in": "N/A",
        "severity": "critical",
        "url": "",
    },
    {
        "issue_id": "AMD-RDNA2-001",
        "title": "GFX pipe hang on Navi21 with heavy compute + graphics mix",
        "chip_gens": ["amd_rdna2"],
        "symptoms": ["gpu_hang", "gfx_cp_event"],
        "workaround": "Set amdgpu.sched_hw_submission=32",
        "fixed_in": "6.1.0",
        "severity": "error",
        "url": "",
    },
    {
        "issue_id": "AMD-RDNA3-001",
        "title": "Navi31 VCN encode hang during HEVC 8K encoding",
        "chip_gens": ["amd_rdna3"],
        "symptoms": ["gpu_hang", "encoder_event"],
        "workaround": "Limit encode to 4K or use H.264",
        "fixed_in": "6.6.0",
        "severity": "error",
        "url": "",
    },
    {
        "issue_id": "AMD-CDNA3-001",
        "title": "MI300X KFD memory allocation failure with > 192GB VRAM",
        "chip_gens": ["amd_cdna3"],
        "symptoms": ["memory_event"],
        "workaround": "Limit per-process VRAM: HSA_OVERRIDE_GFX_VERSION=9.4.2",
        "fixed_in": "Pending",
        "severity": "error",
        "url": "",
    },
    {
        "issue_id": "AMD-MI100-001",
        "title": "Arcturus SDMA timeout on multi-node all-reduce workload",
        "chip_gens": ["amd_cdna1"],
        "symptoms": ["gpu_hang", "timeout_event"],
        "workaround": "Reduce SDMA ring size: amdgpu.sdma_phase_quantum=32",
        "fixed_in": "5.15.0",
        "severity": "error",
        "url": "",
    },
    {
        "issue_id": "AMD-SEV-001",
        "title": "SEV-SNP attestation failure on Zen 4 under heavy load",
        "chip_gens": ["amd_rdna3"],
        "symptoms": ["amd_sev_event"],
        "workaround": "Update PSP firmware to 0x0A0011C3",
        "fixed_in": "Pending",
        "severity": "error",
        "url": "",
    },
    {
        "issue_id": "AMD-RDNA1-001",
        "title": "Navi10 display underrun at 4K144Hz on DCN 2.0",
        "chip_gens": ["amd_rdna1"],
        "symptoms": ["display_event"],
        "workaround": "Reduce refresh rate to 120Hz or lower resolution",
        "fixed_in": "5.10.0",
        "severity": "warning",
        "url": "",
    },
    {
        "issue_id": "AMD-VEGA-001",
        "title": "Vega20 PMFW voltage regulator timeout at high compute load",
        "chip_gens": ["amd_pre_navi"],
        "symptoms": ["power_event", "gpu_hang"],
        "workaround": "Cap TDP: amdgpu-pro-control power limit 250",
        "fixed_in": "5.4.0",
        "severity": "error",
        "url": "",
    },
    {
        "issue_id": "AMD-RDNA2-002",
        "title": "Navi21 IOMMU v2 fault during SR-IOV VF initialization",
        "chip_gens": ["amd_rdna2"],
        "symptoms": ["smmu_fault", "reset_event"],
        "workaround": "Add amd_iommu=off to kernel cmdline for affected VFs",
        "fixed_in": "6.2.0",
        "severity": "error",
        "url": "",
    },
    {
        "issue_id": "AMD-CDNA2-001",
        "title": "MI250X NVLink/XGMI peer access causing GMC TLB storm",
        "chip_gens": ["amd_cdna2"],
        "symptoms": ["memory_event", "gpu_hang"],
        "workaround": "Disable XGMI: amdgpu.xgmi_pstate=0",
        "fixed_in": "6.3.0",
        "severity": "critical",
        "url": "",
    },
    {
        "issue_id": "AMD-RDNA3-002",
        "title": "Navi31 CXL memory controller error under NUMA access",
        "chip_gens": ["amd_rdna3"],
        "symptoms": ["memory_event"],
        "workaround": "Bind to local NUMA node: numactl --membind=0",
        "fixed_in": "Pending",
        "severity": "error",
        "url": "",
    },
    {
        "issue_id": "AMD-CDNA1-001",
        "title": "Arcturus RAS injection test triggering false UE panic",
        "chip_gens": ["amd_cdna1"],
        "symptoms": ["ras_event", "kernel_panic"],
        "workaround": "Disable RAS injection: amdgpu.ras_enable=0",
        "fixed_in": "5.10.0",
        "severity": "critical",
        "url": "",
    },
    {
        "issue_id": "AMD-RDNA2-003",
        "title": "RX 6900 XT thermal throttling causing ring timeout",
        "chip_gens": ["amd_rdna2"],
        "symptoms": ["thermal_event", "gpu_hang"],
        "workaround": "Improve case airflow or undervolt GPU",
        "fixed_in": "N/A",
        "severity": "warning",
        "url": "",
    },
    {
        "issue_id": "AMD-CDNA3-002",
        "title": "MI300A APU unified memory fault during CPU+GPU concurrent access",
        "chip_gens": ["amd_cdna3"],
        "symptoms": ["memory_event", "memory_poison"],
        "workaround": "Use explicit memory barriers in kernel code",
        "fixed_in": "Pending",
        "severity": "critical",
        "url": "",
    },
    {
        "issue_id": "AMD-RDNA1-002",
        "title": "Navi10 MEC firmware assert during OpenCL 3.0 kernel dispatch",
        "chip_gens": ["amd_rdna1"],
        "symptoms": ["gpu_hang", "firmware_event"],
        "workaround": "Use OpenCL 2.0 profile or update linux-firmware",
        "fixed_in": "5.15.0",
        "severity": "error",
        "url": "",
    },
    {
        "issue_id": "AMD-VEGA-002",
        "title": "Vega20 RLC safe mode timeout causing GPU reset loop",
        "chip_gens": ["amd_pre_navi"],
        "symptoms": ["ras_event", "reset_event"],
        "workaround": "Disable RLC safe mode: amdgpu.no_rlcg_accesses=1",
        "fixed_in": "5.10.0",
        "severity": "critical",
        "url": "",
    },
    {
        "issue_id": "AMD-RDNA3-003",
        "title": "Navi31 PCIe BAR size mismatch causing MMIO failure",
        "chip_gens": ["amd_rdna3"],
        "symptoms": ["pcie_error", "memory_event"],
        "workaround": "Enable 4G decoding in BIOS",
        "fixed_in": "6.7.0",
        "severity": "error",
        "url": "",
    },
    {
        "issue_id": "AMD-CDNA2-002",
        "title": "MI250 HBM2e temperature sensor reporting incorrect values",
        "chip_gens": ["amd_cdna2"],
        "symptoms": ["thermal_event"],
        "workaround": "Use external thermal monitoring: rocm-smi --showtemp",
        "fixed_in": "6.1.0",
        "severity": "warning",
        "url": "",
    },
    {
        "issue_id": "AMD-RDNA2-004",
        "title": "Navi21 JPEG engine hang during 8K video decode",
        "chip_gens": ["amd_rdna2"],
        "symptoms": ["gpu_hang"],
        "workaround": "Use VCN for video decode instead of JPEG engine",
        "fixed_in": "6.0.0",
        "severity": "error",
        "url": "",
    },
    {
        "issue_id": "AMD-CDNA3-003",
        "title": "MI300X SMU power capping race during multi-GPU workload",
        "chip_gens": ["amd_cdna3"],
        "symptoms": ["power_event", "gpu_hang"],
        "workaround": "Set static power limit: rocm-smi --setpoweroverdrive 0",
        "fixed_in": "Pending",
        "severity": "error",
        "url": "",
    },
]
