"""Probe manifest — SHA-256 integrity verification for compiled C probes.

[N-SG-07] All C probes under tools/c_probes/ are verified against
probes.sha256 before upload to the target board.

Verification flow:
  1. Read tools/c_probes/probes.sha256 (generated by Makefile)
  2. For each listed binary, compute SHA-256 of local file
  3. Compare against manifest entry
  4. Upload only if all hashes match

Raises ProbeManifestError on any mismatch.
"""

from __future__ import annotations

import hashlib
import os
from pathlib import Path
from typing import Optional

import structlog

log = structlog.get_logger(__name__)


class ProbeManifestError(Exception):
    """Raised when a C probe fails SHA-256 integrity check."""


def _sha256_file(path: str) -> str:
    """Compute SHA-256 of a file. Returns lowercase hex string."""
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def load_manifest(manifest_path: str) -> dict[str, str]:
    """Load a SHA-256 manifest file.

    Format (standard sha256sum output):
        <hex_hash>  <filename>

    Returns dict mapping filename → expected_hash.
    """
    manifest: dict[str, str] = {}
    with open(manifest_path, "r", encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split(None, 1)
            if len(parts) == 2:
                hex_hash, filename = parts
                # Strip leading ./ or path prefix; keep basename
                filename = filename.lstrip("*").strip()
                manifest[os.path.basename(filename)] = hex_hash.lower()
    return manifest


def verify_c_probes(
    c_probes_dir: str,
    manifest_filename: str = "probes.sha256",
) -> dict[str, str]:
    """Verify all C probes listed in the manifest.

    Returns dict of {probe_name: verified_path} for all verified probes.
    Raises ProbeManifestError if any probe fails or is missing.
    """
    probes_dir = Path(c_probes_dir)
    manifest_path = probes_dir / manifest_filename

    if not manifest_path.exists():
        raise ProbeManifestError(
            f"Probe manifest not found: {manifest_path}. "
            "Run 'make' in tools/c_probes/ first."
        )

    manifest = load_manifest(str(manifest_path))
    if not manifest:
        raise ProbeManifestError(f"Empty probe manifest: {manifest_path}")

    verified: dict[str, str] = {}
    errors: list[str] = []

    for probe_name, expected_hash in manifest.items():
        probe_path = probes_dir / probe_name
        if not probe_path.exists():
            errors.append(f"Probe binary missing: {probe_path}")
            continue

        actual_hash = _sha256_file(str(probe_path))
        if actual_hash != expected_hash:
            errors.append(
                f"SHA-256 mismatch for {probe_name}: "
                f"expected={expected_hash[:16]}... got={actual_hash[:16]}..."
            )
        else:
            verified[probe_name] = str(probe_path)
            log.debug("probe_verified", probe=probe_name)

    if errors:
        raise ProbeManifestError(
            "C probe integrity check failed:\n" + "\n".join(f"  {e}" for e in errors)
        )

    log.info("c_probes_verified", count=len(verified))
    return verified


def upload_probe(
    runner: object,
    local_path: str,
    remote_dir: str = "/tmp/poagent_probes",
) -> str:
    """Upload a verified C probe binary to the target board via SCP.

    Returns the remote path of the uploaded probe.
    Requires runner to have an SSH transport with paramiko client.
    """
    probe_name = os.path.basename(local_path)
    remote_path = f"{remote_dir}/{probe_name}"

    ssh_client = getattr(runner, "_ssh_client", None)
    if ssh_client is None:
        raise ProbeManifestError("upload_probe requires SSH transport")

    # Ensure remote directory exists
    runner.exec(f"mkdir -p {remote_dir}", timeout=5.0)  # type: ignore[union-attr]

    # Use paramiko SFTP for upload
    try:
        sftp = ssh_client.open_sftp()
        sftp.put(local_path, remote_path)
        sftp.chmod(remote_path, 0o755)
        sftp.close()
        log.info("probe_uploaded", probe=probe_name, remote=remote_path)
    except Exception as exc:
        raise ProbeManifestError(f"Upload failed for {probe_name}: {exc}") from exc

    # Verify SHA-256 on remote
    local_hash = _sha256_file(local_path)
    result = runner.exec(  # type: ignore[union-attr]
        f"sha256sum {remote_path} 2>/dev/null | awk '{{print $1}}'",
        timeout=10.0,
    )
    remote_hash = result.stdout.strip().lower()
    if remote_hash != local_hash:
        raise ProbeManifestError(
            f"Remote SHA-256 mismatch after upload for {probe_name}: "
            f"local={local_hash[:16]}... remote={remote_hash[:16]}..."
        )

    return remote_path
